name: Deploy(Prod)

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "app/fastapi/**"
      - "app/pgdb/**"
      - "aws/**"
      - ".github/workflows/feature-api-prod-deploy.yaml"

permissions:
  id-token: write
  contents: read

env:
  TF_DEPLOY_FLAG: false # default tf deploy value: false

jobs:
  set-tf-ini:
    name: Get Terraform Flag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Terraform Flag
        id: set_flag
        shell: bash
        run: |
          TF_INI_CONTENT=$(cat aws/terraform.ini | tr -d '\n' | tr '[:upper:]' '[:lower:]')
                   
          if [ "$TF_INI_CONTENT" == "deploy" ]; then
            echo "TF_DEPLOY_FLAG=true" >> "$GITHUB_OUTPUT"
            echo "Setting TF_DEPLOY_FLAG to true (Deploy mode)."
          else
            echo "TF_DEPLOY_FLAG=false" >> "$GITHUB_OUTPUT"
            echo "Setting TF_DEPLOY_FLAG to false (Destroy mode)."
          fi
    outputs:
      TF_DEPLOY_FLAG: ${{ steps.set_flag.outputs.TF_DEPLOY_FLAG }}

  ecr-push-fastapi:
    name: Push Image to ECR - FastAPI(Prod)
    # condition: if ini is true
    needs: set-tf-ini
    if: needs.set-tf-ini.outputs.TF_DEPLOY_FLAG == 'true'
    runs-on: ubuntu-latest
    environment: prod
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      DIR_DOCKFILE: app/fastapi
      ECR_REPOSITORY: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROJECT }}-${{vars.APP}}-fastapi"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN}}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: FastAPI - Extract metadata
        id: fastapi-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.ECR_REPOSITORY }}

      - name: FastAPI - Build and push Docker image
        id: fastapi-push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ env.DIR_DOCKFILE }}
          labels: ${{ steps.fastapi-meta.outputs.labels }}
          tags: "${{ env.ECR_REPOSITORY }}:${{ vars.ENV }}"

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        if: failure()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "${{ job.status }} - ${{ github.workflow }}: ${{ vars.PROJECT}} ${{vars.APP}} (${{vars.ENV}})"
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          html_body: |
            <h2>GitHub Actions CI/CD Notification</h2>
            <p><b>Project</b>: ${{ vars.PROJECT}}</p>
            <p><b>Application</b>: ${{ vars.APP}}</p>
            <p><b>Repository</b>: ${{ github.repository }}</p>
            <p><b>Env</b>: ${{ vars.ENV }}</p>
            <p><b>Job</b>: ${{ github.job }}</p>
            <p><b>Status</b>: ${{ job.status }}</p>
            <p><b>Branch</b>: ${{ github.ref }}</p>
            <p><b>Workflow</b>: ${{ github.workflow }}</p>
            <p><b>Commit</b>: ${{ github.sha }}</p>
            <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>

  ecr-push-pgdb:
    name: Push Image to ECR - Postgres(Prod)
    needs: set-tf-ini
    if: needs.set-tf-ini.outputs.TF_DEPLOY_FLAG == 'true'
    runs-on: ubuntu-latest
    environment: prod
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      DIR_DOCKFILE: app/pgdb
      ECR_REPOSITORY: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROJECT }}-${{vars.APP}}-pgdb"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN}}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Postgres - Extract metadata
        id: postgres-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.ECR_REPOSITORY }}

      - name: Postgres - Build and push Docker image
        id: postgres-push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ env.DIR_DOCKFILE }}
          labels: ${{ steps.postgres-meta.outputs.labels }}
          tags: "${{ env.ECR_REPOSITORY }}:${{ vars.ENV }}"

      - name: Send email notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "${{ job.status }} - ${{ github.workflow }}: ${{ vars.PROJECT}} ${{vars.APP}} (${{vars.ENV}})"
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          html_body: |
            <h2>GitHub Actions CI/CD Notification</h2>
            <p><b>Project</b>: ${{ vars.PROJECT}}</p>
            <p><b>Application</b>: ${{ vars.APP}}</p>
            <p><b>Repository</b>: ${{ github.repository }}</p>
            <p><b>Env</b>: ${{ vars.ENV }}</p>
            <p><b>Job</b>: ${{ github.job }}</p>
            <p><b>Status</b>: ${{ job.status }}</p>
            <p><b>Branch</b>: ${{ github.ref }}</p>
            <p><b>Workflow</b>: ${{ github.workflow }}</p>
            <p><b>Commit</b>: ${{ github.sha }}</p>
            <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>

  # ecr-push-redis:
  #   name: Push Image to ECR - Redis(Prod)
  #   runs-on: ubuntu-latest
  #   environment: prod
  #   env:
  #     AWS_REGION: ${{ vars.AWS_REGION }}
  #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  #     DIR_DOCKFILE: app/redis
  #     ECR_REPOSITORY: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROJECT }}-${{vars.APP}}-redis"

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Configure AWS credentials (OIDC)
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN}}
  #         aws-region: ${{ vars.AWS_REGION }}

  #     - name: Login to Amazon ECR
  #       id: login-ecr
  #       uses: aws-actions/amazon-ecr-login@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Redis - Extract metadata
  #       id: redis-meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: ${{ env.ECR_REPOSITORY }}

  #     - name: Redis - Build and push Docker image
  #       id: redis-push
  #       uses: docker/build-push-action@v3
  #       with:
  #         push: true
  #         context: ${{ env.DIR_DOCKFILE }}
  #         labels: ${{ steps.redis-meta.outputs.labels }}
  #         tags: "${{ env.ECR_REPOSITORY }}:${{ vars.ENV }}"

  #     - name: Send email notification
  #       if: failure()
  #       uses: dawidd6/action-send-mail@v3
  #       with:
  #         server_address: smtp.gmail.com
  #         server_port: 465
  #         secure: true
  #         username: ${{ secrets.EMAIL_USERNAME }}
  #         password: ${{ secrets.EMAIL_PASSWORD }}
  #         subject: "${{ job.status }} - ${{ github.workflow }}: ${{ vars.PROJECT}} ${{vars.APP}} (${{vars.ENV}})"
  #         to: ${{ secrets.EMAIL_USERNAME }}
  #         from: ${{ secrets.EMAIL_USERNAME }}
  #         html_body: |
  #           <h2>GitHub Actions CI/CD Notification</h2>
  #           <p><b>Project</b>: ${{ vars.PROJECT}}</p>
  #           <p><b>Application</b>: ${{ vars.APP}}</p>
  #           <p><b>Repository</b>: ${{ github.repository }}</p>
  #           <p><b>Env</b>: ${{ vars.ENV }}</p>
  #           <p><b>Job</b>: ${{ github.job }}</p>
  #           <p><b>Status</b>: ${{ job.status }}</p>
  #           <p><b>Branch</b>: ${{ github.ref }}</p>
  #           <p><b>Workflow</b>: ${{ github.workflow }}</p>
  #           <p><b>Commit</b>: ${{ github.sha }}</p>
  #           <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>

  # deploy:
  #   name: Deploy(Prod)
  #   needs:
  #     - ecr-push-fastapi
  #     - ecr-push-pgdb
  #     - ecr-push-redis
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 90
  #   environment: prod
  #   env:
  #     TF_DIR: aws
  #     TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
  #     TF_VAR_aws_region: ${{ vars.AWS_REGION }}
  #     TF_VAR_env: ${{ vars.ENV }}
  #     TF_VAR_aws_ecr_fastapi: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROJECT }}-${{vars.APP}}-fastapi"
  #     TF_VAR_aws_ecr_pgdb: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROJECT }}-${{vars.APP}}-pgdb"
  #     TF_VAR_aws_ecr_redis: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROJECT }}-${{vars.APP}}-redis"
  #     TF_VAR_app_pgdb_host: ${{ vars.APP_PGDB_HOST }}
  #     TF_VAR_app_pgdb_db: ${{ vars.APP_PGDB_DB }}
  #     TF_VAR_app_pgdb_user: ${{ vars.APP_PGDB_USER }}
  #     TF_VAR_app_pgdb_pwd: ${{ secrets.APP_PGDB_PWD }}
  #     TF_VAR_app_redis_host: ${{ vars.APP_REDIS_HOST }}
  #     TF_VAR_app_pgdb_init_user: ${{ vars.APP_PGDB_INIT_USER }}
  #     TF_VAR_app_pgdb_init_db: ${{ vars.APP_PGDB_INIT_DB }}
  #     TF_VAR_app_pgdb_init_pwd: ${{ secrets.APP_PGDB_INIT_PWD }}
  #     TF_VAR_cloudflare_api_token: ${{ secrets.CF_API_TOKEN }}
  #     TF_VAR_cloudflare_zone_id: ${{ secrets.CF_ZONE_ID }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: ${{ vars.TF_VERSION }}

  #     - name: Configure AWS credentials (OIDC)
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN}}
  #         aws-region: ${{ vars.AWS_REGION }}

  #     - name: Configure Terraform plugin cache
  #       run: |
  #         mkdir -pv ${{ env.TF_PLUGIN_CACHE_DIR }}
  #         echo 'plugin_cache_dir = "${{ env.TF_PLUGIN_CACHE_DIR }}"' > ~/.terraformrc

  #     - name: Cache Terraform plugins
  #       uses: actions/cache@v4
  #       with:
  #         path: ${{ env.TF_PLUGIN_CACHE_DIR }}
  #         key: ${{ runner.os }}-terraform-${{ vars.TF_VERSION }}

  #     - name: Terraform init - S3 backend
  #       working-directory: ${{ env.TF_DIR }}
  #       run: |
  #         terraform init -reconfigure -input=false \
  #           -backend-config="bucket=${{ vars.AWS_BACKEND_BUCKET }}" \
  #           -backend-config="region=${{ vars.AWS_REGION }}" \
  #           -backend-config="key=${{ vars.PROJECT }}-${{vars.APP}}/${{ vars.ENV }}/terraform.tfstate" \
  #           -backend-config="encrypt=true"

  #     - name: Terraform Validate
  #       working-directory: ${{ env.TF_DIR }}
  #       run: |
  #         terraform fmt -check -recursive -no-color
  #         terraform validate -no-color

  #     - name: Terraform Plan
  #       working-directory: ${{ env.TF_DIR }}
  #       id: plan
  #       run: terraform plan -out=tfplan -input=false -no-color

  #     - name: Show plan (JSON)
  #       working-directory: ${{ env.TF_DIR }}
  #       run: terraform show -json tfplan > tfplan.json

  #     - name: Save plan artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: tfplan-bundle
  #         path: |
  #           ${{ env.TF_DIR }}/tfplan
  #           ${{ env.TF_DIR }}/tfplan.json
  #         retention-days: 3

  #     - name: Terraform Apply
  #       working-directory: ${{ env.TF_DIR }}
  #       run: terraform apply -auto-approve -no-color tfplan

  #     - name: Send email notification
  #       if: always()
  #       uses: dawidd6/action-send-mail@v3
  #       with:
  #         server_address: smtp.gmail.com
  #         server_port: 465
  #         secure: true
  #         username: ${{ secrets.EMAIL_USERNAME }}
  #         password: ${{ secrets.EMAIL_PASSWORD }}
  #         subject: "${{ job.status }} - ${{ github.workflow }}: ${{ vars.PROJECT}} ${{vars.APP}} (${{vars.ENV}})"
  #         to: ${{ secrets.EMAIL_USERNAME }}
  #         from: ${{ secrets.EMAIL_USERNAME }}
  #         html_body: |
  #           <h2>GitHub Actions CI/CD Notification</h2>
  #           <p><b>Project</b>: ${{ vars.PROJECT}}</p>
  #           <p><b>Application</b>: ${{ vars.APP}}</p>
  #           <p><b>Repository</b>: ${{ github.repository }}</p>
  #           <p><b>Env</b>: ${{ vars.ENV }}</p>
  #           <p><b>Job</b>: ${{ github.job }}</p>
  #           <p><b>Status</b>: ${{ job.status }}</p>
  #           <p><b>Branch</b>: ${{ github.ref }}</p>
  #           <p><b>Workflow</b>: ${{ github.workflow }}</p>
  #           <p><b>Commit</b>: ${{ github.sha }}</p>
  #           <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>
